### ISSUE TITLE
When does the browser act on changes?

### ISSUE THREAD

**Issue by martinthomson** [w3c/mst-content-hint#17]
Obviously, if a stream is actively being encoded, the browser isn't going to change its posture mid-frame.  An unsupported value might cause the browser to never change its posture.  This needs some advice, and maybe a feedback mechanism.

**Comment by pbos** [comment]
Is clarifying this useful? The browser is permitted to change its posture mid-frame and re-encode it, should it want to, but that seems like a very clunky approach to implementing this, and if it takes minutes to apply it's compliant but a "not very good" implementation. Given that no behavior is strictly defined for any of these, a no-op is also valid behavior, which is indistinguishable from this value taking years to propagate.

**Comment by martinthomson** [comment]
If it doesn't matter, say so.

**Comment by pbos** [comment]
Does changing "should adapt its decision" to something like "should adapt its decision as soon as possible" or "as soon as feasible" sound good to you?

**Comment by martinthomson** [comment]
It doesn't have to be ASAP.  The point is that there needs to be some expectation on the part of the application about what is going to happen.  That could be that it has no expectation that anything happens.  Establishing that there can be no expectation is OK in this case.

**Comment by pbos** [comment]
Sorry that it took quite a bit to get around to it, please look at the updated text and see if that's reasonable to you. :)
