### ISSUE TITLE
Gather interest from browser vendors/web developers.

### ISSUE THREAD

**Issue by pbos** [w3c/mst-content-hint#19]
An implementation is available in Chromium ToT/Chrome Canary as part of https://crbug.com/653531. Working on a GitHub demo that should help generate more public interest. This can be documented here in future support of an intent to ship.

**Comment by pbos** [comment]
This demo is now up at: https://webrtc.github.io/samples/src/content/capture/video-contenthint/

**Comment by pbos** [comment]
FWIW: Typical usecase for this is screencasting any video content or fast-paced games.

**Comment by benbro** [comment]
I have a use case for content-hint support in MediaRecorder.
It'll be great to be able to dynamically change the hint depending on what I draw on the canvas.

**Comment by pbos** [comment]
This just moved over to https://github.com/w3c so considering this closed.
