### ISSUE TITLE
Stratify the model into private variables and public getter/setter

### ISSUE THREAD

**Issue by domenic** [w3c/mst-content-hint#2]
We want to define something like: `Each <code>MediaStreamTrack</code> has an associated <dfn>author-set content-type hint</dfn>, initially null`. (Let's say `null` for now.)

Then we define: The `<dfn>mediaContentTypeHint</dfn>, on getting, ...` and `The <code>mediaContentTypeHint</code>, on setting, ...` with algorithms (or just a sentence) stating how they change or return `this <code>MediaStreamTrack</code>'s <a>author-set content-type hint</a>`.

**Comment by domenic** [comment]
Oh, and I forgot: you also will want to add some algorithm like "To <dfn>get the media content type hint</dfn> for a MediaStreamTrack _track_, perform the following steps:" which uses _track_'s associated author-set content-type hint, but also uses other information. This would be what browsers would actually implement.

**Comment by pbos** [comment]
Please re-open this or any of the other ones if it still seems off.
