### ISSUE TITLE
Maybe s/fluid/motion/ ?

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mst-content-hint#20]
To limit expectations, `contentHint` values should be descriptive, not prescriptive.

`"music"` and `"speech"` are neutral descriptions of content.

`"fluid"` could be confused with a positive quality, a feature. That's bad, because seen as a control surface, it becomes unclear how other control surfaces like `degradationPreference` compete.

A more neutral `"motion"` might curb expectations better.

**Comment by pbos** [comment]
I'm fine with either, motion is fine to me too.

**Comment by pbos** [comment]
I think "motion" describes the content better too. Something that moves a lot might not have fluid/linear motion.

**Comment by pbos** [comment]
Do you agree @alvestrand? I'd like to have another nod before replacing everything. :)

**Comment by pthatcherg** [comment]
"motion" sounds good to me.  It makes them all nouns (I think "fluid" in this context was an adjective).

**Comment by pbos** [comment]
Peter, do you think we should change "detailed" to "detail" too then? I think "motion" and "detail" match eachother better.

**Comment by pthatcherg** [comment]
"Detail" is a noun, which is more consistent with the others, which are nouns.
