### ISSUE TITLE
Intent to Migrate to WebRTC Working Group

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/mst-content-hint#22]
# Supporter emails

dom@w3.org, hta@google.com,  pbos@google.com 

Proposal

https://wicg.github.io/mst-content-hint/

# Summary

 This specification extends MediaStreamTrack to provide a media-content hint attribute. This optional hint permits MediaStreamTrack consumers such as PeerConnection (defined in [webrtc]) or MediaRecorder (defined in [mediastream-recording]) to encode or process track media with methods more appropriate to the type of content that is being consumed.

# Motivation and Use Cases

Adding a media-content hint provides a way for a web application to help track consumers make more informed decision of what encoder parameters and processing algorithms to use on the consumed content. 

# Compatibility Risk

This is conceived as a hint which user agents can ignore; as a result, the compatibility risk seems limited.

# Ongoing technical constraints

User agents will need to map the hints to video codecs they have support for, and keep that mapping updated on an ongoing basis.

# Link to implementation experience and demos

https://www.chromestatus.com/feature/5689466211532800

# Data

N/A

# Security and Privacy

No identified impact on security and privacy

# Accessibility

No identified impact on accessibility.

# Internationalization

No identified impact on I18N

**Comment by marcoscaceres** [comment]
This looks great! when you transfer this, can you just add a link to the a WG decision/resolution to take this work on?

Also, I noticed in the list link to implementation above that only Google has given public signals. Is it worth asking for a "[Mozilla position](http://github.com/mozilla/standards-positions/)" from our WebRTC folks? This is probably not needed if they gave a +1 on a working group call already.

**Comment by dontcallmedom** [comment]
[Working Group decision to adopt](https://lists.w3.org/Archives/Public/public-webrtc/2018Mar/0067.html)

(re Mozilla's position, different folks from Mozilla expressed different opinions on the topic during [the latest call where this was discussed](https://www.w3.org/2018/02/21-webrtc-minutes#item02))

**Comment by dontcallmedom** [comment]
Now transfered https://github.com/w3c/mst-content-hint/issues
