### ISSUE TITLE
Adding "text" as a content-hints value

### ISSUE THREAD

**Issue by aboba** [w3c/mst-content-hint#23]
There are scenarios where it would be useful not just to have a "detail" hint, but a "text" hint as well.  For example, a "text" hint could be used to hint that AV1 intra-block copy could be useful.

**Comment by alvestrand** [comment]
"Text" would be a stronger hint than "detail" - saying that there's likely to be many sharp edges whose exact shape is important, and that there may be blocks of color (the background) that are best rendered as uniform color.

**Comment by aboba** [comment]
@alvestrand  Yes - "text" carries some of the same connotations as "detail" in terms of a  preference for resolution over framerate, but also would likely result in additional optimizations (e.g. use of AV1 intra-block copy).
