### ISSUE TITLE
Interaction with degradationPreference

### ISSUE THREAD

**Issue by aboba** [w3c/mst-content-hint#24]
In current Edge, a `degradationPreference` value of "maintain-resolution" is interpreted similarly to the "detail" content-hint.

This raises the question of what happens when the value of  `degradationPreference` may appear to conflict with the value of the content-hint.  For example:

- If `degradationPreference` is set to the default value of "balanced",  does this override the value of content-hint? 

- If `degradationPreference` is set to "maintain-framerate", does this override a content-hint of "detail" or "text"? 

- If `degradationPreference` is set to "maintain-resolution", does this override a content-hint of "motion"?

**Comment by aboba** [comment]
During one of the virtual interims it was suggested that content-hints can be overridden by more specific guidance elsewhere in the API. One other attribute that has been used for encoder guidance is `degradationPreference`, though its use is likely to be under-specified. Some questions: 

1. What happens if `kind` has a value of `video` while `degradationPreference` is set to "maintain-resolution" and the content-hint is "text"?  "text" implies a focus on resolution/detail, and provides more information than "detail" or "maintain-resolution", so IMHO this is not a case of more specific guidance and optimizing the encoding for "text" makes sense. 

2. What happens if `kind` has a value of `video` while `degradationPreference` is set to "maintain-framerate" and the content-hint is something other than `motion`?  Here I would suggest that  `degradationPreference` override the content-hint, since they contradict each other. 

3. What happens if codec settings conflict with a content-hint? Here I would suggest that the codec settings take preference.

**Comment by aboba** [comment]
Florent has noted that in the Chrome implementation, content-hints only influence the encoder but not the tradeoff between resolution and framerate. In such an implementation, there is no interaction between content-hints and `degradationPreference`.

**Comment by alvestrand** [comment]
I think this was addressed - degradationPreference is now defined in terms of content-hints, but is able to override it.
Closing - please reopen if disagree.
