### ISSUE TITLE
Reduncancy and lack of normative clarity around interaction with constraints

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mst-content-hint#28]
This spec loosely mentions *"Echo-cancellation"*, *"noise suppression"*, and *"boost intelligibility of the incoming signal"* (autoGainControl?) and implies a control surface to those features.

There seems to be significant overlap here with track *constraints*. E.g.:
```js
track.contentHint = "music";
await track.applyConstraints({
  echoCancellation: true,
  noiseSuppression: true,
  autoGainControl: true,
});
track.contentHint = "music";
console.log(track.getSettings().echoCancellation); // true or false?
console.log(track.getSettings().noiseSuppression); // true or false?
console.log(track.getSettings().autoGainControl);  // true or false?
```
My guess would be `true` on account of *"These settings are not intended to replace encoder-level settings completely but rather complement them with a simpler hint"*—even though we're not dealing with encoders here.

There also seems to be a missed opportunity here to make things normatively testable. E.g.:
```js
// Assuming unconstrained track
track.contentHint = "music";
console.log(track.getSettings().echoCancellation); // false
console.log(track.getSettings().noiseSuppression); // false
console.log(track.getSettings().autoGainControl);  // false
```

The lack of testable steps feels like a general problem, so I'll open a separate issue on that.

**Comment by aboba** [comment]
Related Issue (for video): https://github.com/w3c/mst-content-hint/issues/24

**Comment by alvestrand** [comment]
I think this is addressed now - please reopen if not.
