### ISSUE TITLE
Decide on what the default value is

### ISSUE THREAD

**Issue by domenic** [w3c/mst-content-hint#3]
I see three possibilities: `"auto"`, `""`, and `null`. Let's eliminate `"auto"`, since the other two options allow useful code like

``` js
if (track.mediaContentTypeHint) {
  ...
}
```

which seems plausibly useful. Now we need to select between `""` and `null`.

I don't have a good intuition for which is better. Let me ask around.

If we do `null`, the type needs to change to `DOMString?`

**Comment by domenic** [comment]
Some precedents for "" is https://fetch.spec.whatwg.org/#enumdef-requestdestination and https://html.spec.whatwg.org/multipage/embedded-content.html#canplaytyperesult. As such I'm leaning in that direction...

**Comment by annevk** [comment]
It depends a bit on the semantics I would say. "null" is a little weird-looking (for things other than origins anyway).

**Comment by domenic** [comment]
I meant the literal `null`, not the string `"null"`.

**Comment by annevk** [comment]
Oh you said null. I think nullable enums are an anti-pattern. No need for different types.

**Comment by pbos** [comment]
Please re-open or open another one if this DOMString + two different enums trick is bad. It's now a DOMString which allows "", or the enumeration corresponding to the MediaStreamTrack `kind` (one for audio, one for video).
