### ISSUE TITLE
Wide review

### ISSUE THREAD

**Issue by caribouW3** [w3c/mst-content-hint#44]
Per [Document review guidance](https://www.w3.org/wiki/DocumentReview#Horizontal_Groups):
 
* [x]  [I18N review request](https://github.com/w3c/i18n-request/issues/125)
* [x]  [TAG review request](https://github.com/w3ctag/design-reviews/issues/539)
* [x]  [Privacy review request](https://lists.w3.org/Archives/Public/public-privacy/2020JulSep/0012.html)
* [ ]  [Accessibility review request](https://lists.w3.org/Archives/Public/public-apa/2020Jul/0031.html)
* [x]  [Security review request](https://lists.w3.org/Archives/Public/public-web-security/2020Jul/0005.html)
* [ ]  [Chairs review request](https://lists.w3.org/Archives/Member/chairs/2020JulSep/0026.html)

And usual groups:

* [ ]  [Media & Entertainment Interest Group](https://lists.w3.org/Archives/Public/public-web-and-tv/2020Jul/0019.html)
* [ ]  [Media Working Group](https://lists.w3.org/Archives/Public/public-media-wg/2020Jul/0003.html)

**Comment by samuelweiler** [comment]
Security reviewer reports no issues.

**Comment by caribouW3** [comment]
Privacy review in https://github.com/w3c/mst-content-hint/issues/51
