### ISSUE TITLE
Why are arbitrary values disallowed for hints?

### ISSUE THREAD

**Issue by kenchris** [w3c/mst-content-hint#47]
In reference to https://github.com/w3ctag/design-reviews/issues/539

Why are arbitrary values (anything aside from well-known values or "", since on the surface it is a DOMString property) disallowed for hints? (Wasn't quite clear from the spec; is it because internally [e.g. during transport] these values are encoded into enums?)

**Comment by aboba** [comment]
content-hints are required to be specific enough to demonstrate interoperability between browsers. Allowing arbitrary values with no specified behavior would not allow for development of WPT tests or a demonstration of interoperability, and therefore such a specification could not advance as a W3C specification.

**Comment by kenchris** [comment]
@cynthia

**Comment by alvestrand** [comment]
The mst-content-hints are processing instructions from the JS application to the Web platform.
If an implementation  of the Web platform gets an arbitrary string, there are two possibilities:

- The implementation ignores the string. This seems harmless, but not useful.
- The implementation takes action on the string in a way that is not predictable to the application. This seems actively harmful to interoperability.

Thus, we decided to allow only setting values with a defined meaning (note that extensions to the spec may define more meanings).

Allowing only setting of values that have an interpretation by the platform allows feature detection on whether the platform supports that particular value.

**Comment by alvestrand** [comment]
@kenchris @cynthia is the question adequately addressed? Does the spec need more text to make this choice clear?

**Comment by alvestrand** [comment]
No more comments, so closing.
