### ISSUE TITLE
Client/server-side question

### ISSUE THREAD

**Issue by kdeqc** [w3c/mst-content-hint#50]
Hi -

My name's Kris Chapman, and I am handling the privacy review for this proposal.  One of the questions I have is whether or not this is purely a client-side/JavaScript concept or if there is a server-side aspect as well?  It could just be a naming confusion, but I thought I saw something about an associated client hint, but I can't find it again.  So I'm just asking to make sure I have it straight.

Thanks!

**Comment by alvestrand** [comment]
I don't quite understand the question - it is a hint that is set in Javascript and interpreted by the UA (browser). There is nothing in this document that speaks to anything that is communicated with a server of any type (the hint will influence the encoding of audio and video, which may in turn be stored or sent across the network, but there's no concept of "server" involved in these processes).

If "client" is the browser + the Javascript being run in it, and "server" is the entity that one addresses HTTP requests to, then it's safe to say that this is purely a client-side concept.

Did this answer the question?

**Comment by kdeqc** [comment]
Thanks, that does answer my question.  I thought I'd seen something where a client hint request header was also set with the value, but I probably just misread client hint instead of content hint.
