### ISSUE TITLE
Figure out how to get cross-linking working to the various IDL interfaces and attributes mentioned

### ISSUE THREAD

**Issue by domenic** [w3c/mst-content-hint#7]
E.g. a mention of `MediaStreamTrack` should link to its definition in the [GETUSERMEDIA] spec.

I don't know how to do this with ReSpec, personally. But hopefully some quality time with https://github.com/w3c/respec/wiki/User's-Guide will help. You can always call on marcosc if you get stuck. (Purposefully not @-mentioning him yet.)

**Comment by pbos** [comment]
@alvestrand do you know how to do this in ReSpec? I want MediaStreamTrack and its kind attribute to link to the [[!GETUSERMEDIA]] spec and I figure you might've done so a couple of times before?

**Comment by alvestrand** [comment]
From the webrtc spec, I see this:

`<p>The term <dfn>Blob</dfn> is defined in [[!FILEAPI]].</p>`

where the <dfn> tag says "this is the definition".

Then you can say `<a>Blob</a>` elsewhere, and that will be linked to this sentence, where [[FILEAPI]] in turn links to the spec. I don't know how to make the link jump in just one hop.
