### ISSUE TITLE
Is "content type" confusing with the Content-Type header?

### ISSUE THREAD

**Issue by domenic** [w3c/mst-content-hint#9]
I think it would not be confusing if "content type" a well-known phrase for this sort of thing in the RTC/media domains. But if not, then maybe something like just `contentHint` would avoid confusion.

**Comment by pbos** [comment]
@alvestrand what do you think? I haven't found a name I really like for this, in tip of tree it's now `contentTypeHint`.

**Comment by alvestrand** [comment]
In RTP / MIME, "content type" is indeed something different.
"Content form hint" might be better.
I see that "Media stream type" is used in some of our code in some places - "mediaStreamContentHint" might be a long-winded way of putting it.

**Comment by domenic** [comment]
@alvestrand what do you think of `contentHint`? As in, `myMediaStream.contentHint = "fluid"`.

**Comment by alvestrand** [comment]
"contentHint" works for me.

**Comment by pbos** [comment]
Sorry, I did a force-push, this was closed in 5d18ab137575aba5f5735f9d3a96732f9717500d.
